# Generated by Django 4.1.4 on 2023-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_image_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='0608878266', max_length=150, verbose_name='telephone'),
        ),
    ]
