# Generated by Django 4.1.4 on 2023-02-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='0608878266', max_length=15, verbose_name='telephone'),
        ),
    ]
