# Generated by Django 4.1.4 on 2023-02-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_address_phone_address_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_number',
        ),
    ]
