# Generated by Django 4.1.4 on 2023-02-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='0608878266', max_length=15, verbose_name='telephone'),
        ),
    ]
